### ISSUE TITLE
Ability to add javadocs to classes, protocols, methods/functions and properties

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-bro-gen#1]
This won't replace proper framework documentation and tutorials (similar to what MonoTouch has) but it's a first step. Possibly a separate file could be used, so we don't mess with the main yaml file.
In the end we should be able to use the online framework documentation from Apple as Javadocs.

**Comment by badlogic** [comment]
Moved to https://github.com/robovm/robovm-bro-gen-proprietary/issues/4
